# Generated by Django 5.2.4 on 2025-07-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='availability',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
