# Generated by Django 5.2.4 on 2025-07-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='longitude',
            field=models.FloatField(default='0.0'),
            preserve_default=False,
        ),
    ]
